---
- hosts: webservers
  become: true
  tasks:
  - name: Install git
    yum: name=git state=present
  - name: Install wget
    yum: name=wget state=absent
- hosts: appservers
  become: true
  tasks:
  - name: Install zip
    yum: name=zip state=present
  - name: Install httpd
    yum: name=httpd state=latest
