---
- hosts: webservers
  become: true
  tasks:
  - name: Install git
    yum: name=git state=present
    tags:
     - git
  - name: Install Httpd
    yum: name=httpd state=present
    tags:
    - httpd
  - name: Install zip
    yum: name=zip state=present
    tags:
    - zip
  - name: Install wget
    yum: name=wget state=present
    tags:
    - wget
